<?php

/**
 * Smartlook integration plugin.
 *
 * @category  Extension
 * @package   Smartlook
 * @author    Smartsupp <vladimir@smartsupp.com>
 * @copyright 2018 - 2019 Smartsupp.com
 * @license   http://opensource.org/licenses/gpl-license.php GPL-2.0+
 * @link      http://www.smartsupp.com
 *
 * Plugin Name:       Smartsupp Live Chat
 * Plugin URI:        https://www.smartlook.com
 * Description:       Adds Smartlook code to Magento 2.x
 * Version:           2.0.3
 * Author:            Smartsupp
 * Author URI:        http://www.smartsupp.com
 * Text Domain:       smartsupp
 * License:           GPL-2.0+
 * License URI:       http://www.gnu.org/licenses/gpl-2.0.txt
 */

$config = @file_get_contents(__DIR__ . '/../../../etc/config.json');

if ($config === FALSE) {
	$config = ['chatKey' => NULL];
} else {
	$config = json_decode($config, JSON_OBJECT_AS_ARRAY);
}

if ($config['chatKey'] !== NULL) {
	echo '<script type="text/javascript">
		window.smartlook||(function(d) {
		var o=smartlook=function(){ o.api.push(arguments)},h=d.getElementsByTagName(\'head\')[0];
		var c=d.createElement(\'script\');o.api=new Array();c.async=true;c.type=\'text/javascript\';
		c.charset=\'utf-8\';c.src=\'//rec.smartlook.com/recorder.js\';h.appendChild(c);
		})(document);
		smartlook(\'init\', \'' . $config['chatKey'] . '\');';

	$om = \Magento\Framework\App\ObjectManager::getInstance();

	$customerSession = $om->get('Magento\Customer\Model\Session');
	if ($customerSession->isLoggedIn()) {
		echo 'smartlook(\'tag\', \'email\', ' . json_encode($customerSession->getCustomer()->getEmail()) . ');';
		echo 'smartlook(\'tag\', \'name\', ' . json_encode($customerSession->getCustomer()->getName()) . ');';
		echo 'smartlook(\'tag\', \'id\', ' . json_encode($customerSession->getCustomer()->getId()) . ');';
	}

	echo '</script>';
}
